language: go
before_install:
  - GO111MODULE=off go get github.com/aprice/embed/cmd/embed
  - GO111MODULE=off go get golang.org/x/tools/cmd/goimports
  - GO111MODULE=off go get github.com/xo/xo
go:
  - 1.11.4
env:
  - GO111MODULE=on